### PR TITLE
fix: treat paths as absolute paths 

### LINKED ISSUE #131: Use absolute paths internally instead of relative paths
Currently all paths are treated as relative to the chompfile. We should shift the internal representation to always use absolute paths.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #131 

This my first Rust PR ever, so I'd like to hear suggestions and what other paths need to be absolute in the source code, some hints may help!

### CODE REVIEW

**Comment by guybedford** [comment]
Glad to introduce you to Rust! Highly recommend learning it.

So in task.rs there are a bunch of strings which are actually paths, in particular the `target` and `dep` strings. For example the `Job` struct has `targets` and `deps` strings on it which are relative paths - https://github.com/guybedford/chomp/blob/main/src/task.rs#L99.

There is quite a lot of wiring going on there. In theory if the tests pass we should be good though.

One other weird thing is rust canonicalizes windows paths into extended path format, something like `//?/....` if I recall correctly. that may invalidate some other assumptions about how paths are structured.

If you can get comfortable with debugging via `println!` and `dbg!` it should be possible to trace the logics and handle any cases that come up. Don't feel discouraged though it's not an easy job either, but thanks for giving it a shot!

**Comment by Aslemammad** [comment]
@guybedford Thank you so much for the opportunity, solving this would help me so much with learning rust!

**Comment by guybedford** [comment]
This is looking great, nice work. Does it handle windows path canonicalization? We should definitely have tests to land this feature.

Here are some cases that come to mind:

```toml
[[task]]
target = '../output.txt'
deps = ['../input.txt', './another.txt']
```

And ensuring that works.

Also worth checking globbing works:

```toml
[[task]]
deps = ['../*.txt']
```

And also interpolation:

```toml
[[task]]
target = '../#.output'
deps = ['./input/#.input']
```

And interpolation with globbing:

```toml
[[task]]
deps = ['../*.output']
```

**Comment by Aslemammad** [comment]
I'll work on these tests so we can deliver this properly, Thanks for the hints.

File: src/task.rs [hunk 1]
```diff
@@ -1003,13 +1012,17 @@ impl<'a> Runner<'a> {
...
+        let mut target = if task.targets.len() == 0 {
             "".to_string()
         } else if let Some(interpolate) = &job.interpolate {
             replace_interpolate(&task.targets[target_index], interpolate)
         } else {
             task.targets[target_index].clone()
         };
+        if target.len() != 0 {
+            target = target;
+        }
```
Comment (guybedford) [inline src/task.rs:1024]: What is this doing?

File: src/chompfile.rs [hunk 2]
```diff
@@ -215,13 +208,9 @@ impl ChompTaskMaybeTemplated {
     pub fn targets_vec(&self) -> Result<Vec<String>> {
         if let Some(ref target) = self.target {
             let target_str = target.to_string();
-            validate_path(&target_str)?;
             Ok(vec![target_str])
         } else if let Some(ref targets) = self.targets {
             let targets = targets.clone();
-            for target in &targets {
-                validate_path(&target)?;
```
Comment (guybedford) [inline src/chompfile.rs:223]: What if we literally replaced `validate_path` in these loops with doing the canonicalization here at this lower level rather than at all consumer positions?

File: src/task.rs [hunk 3]
```diff
@@ -2342,3 +2360,76 @@ impl<'a> Runner<'a> {
...
+            _ => {
+                normalized.push(component);
+            }
+        }
+    }
+    if ends_with_slash {
+        normalized.push("");
+    }
+    normalized
+}
```
Comment (guybedford) [inline src/task.rs:2435]: Is it possible to directly reference a library for this stuff or do you think we need to have this logic in the source?

**Review by guybedford — COMMENTED** [review]
Great work! Amazing to see that the tests are already passing (short of the Svelte issue).

Is it still possible to get those cases included that I mentioned before?

Had one suggestion re simplifying to treat the `chompfile.rs` as the normalization home, and try to minimize work on consumer end by ensuring all paths are already "canonical" by the time they are accessed. Otherwise we continually play whack a mole with these code paths...

File: src/task.rs (hunk 3 above)
Comment (Aslemammad) [reply src/task.rs:2435]: I couldn't find a proper library for these, so If you think there's a one, please let me know! Though I think these are small and minimal functions.

File: src/task.rs (hunk 1 above)
Comment (Aslemammad) [reply src/task.rs:1024]: it was a refactor thing, let me remove it.

**Comment by Aslemammad** [comment]
I tried including those cases in the test/chompfile, you can check it out in the changes.

File: src/chompfile.rs [hunk 4]
```diff
@@ -214,36 +213,52 @@ impl ChompTaskMaybeTemplated {
...
             Ok(vec![])
         }
     }
-    pub fn deps_vec(&self) -> Result<Vec<String>> {
+    pub fn deps_vec(&self, chompfile: &Chompfile) -> Result<Vec<String>> {
+        let names = chompfile
+            .task
+            .iter()
+            .map(|t| t.name.clone().map(|t| t).unwrap_or_default())
+            .collect::<Vec<_>>();
```
Comment (guybedford) [inline src/chompfile.rs:230]: Rather than creating this vector by copy everytime, you should just be able to directly search `chompfile.task`.

File: src/chompfile.rs [hunk 5]
```diff
@@ -214,36 +213,52 @@ impl ChompTaskMaybeTemplated {
...
+
         if let Some(ref dep) = self.dep {
-            let dep_str = dep.to_string();
-            validate_path(&dep_str)?;
+            let dep_str = if names.contains(dep) || skip_special_chars(dep) {
```
Comment (guybedford) [inline src/chompfile.rs:233]: So instead of `names.contains` you should just be able to do `chompfile.task.iter().find(|&&t| t.name == dep).is_some()` kind of thing.

**Review by guybedford — COMMENTED** [review]
Great to see this working out! Did you try using the file watcher and server with this work yet? The watcher may need to emit full paths itself as well.

I think we're getting close to being able to merge this.

**Comment by Aslemammad** [comment]
@guybedford Fixed those suggestions. Thanks. I tried `watch` and `serve` and they work pretty well, let me know if you find any issues.

**Comment by guybedford** [comment]
Were files rerunning eg interpolated builds properly under watch? I would
check that manually before merging.

For the correction - the point is to avoid any copy eg like using to owned.
Rather you could do a filter first to filter to just those tasks with a
name then do an unwrap and direct string equality check without copying.

File: src/chompfile.rs [hunk 6]
```diff
@@ -214,36 +213,46 @@ impl ChompTaskMaybeTemplated {
...
+                resolve_path(&dep.to_string())
+            };
             Ok(vec![dep_str])
         } else if let Some(ref deps) = self.deps {
-            let deps = deps.clone();
-            for dep in &deps {
-                validate_path(&dep)?;
-            }
+            let deps = deps
+                .clone()
```
Comment (guybedford) [inline src/chompfile.rs:235]: Avoid clone!

File: src/chompfile.rs [hunk 7]
```diff
@@ -214,36 +213,46 @@ impl ChompTaskMaybeTemplated {
...
+                .iter()
+                .map(|dep| {
+                    if chompfile.task.iter().find(|t| t.name.to_owned().unwrap_or_default().contains(dep)).is_some() || skip_special_chars(dep) {
```
Comment (guybedford) [inline src/chompfile.rs:238]: Maybe something more like:

```rust
// this should be a list of references, without copying
const existing_task_names = chompfile.task.filter(|&t| t.name.is_some()).map(|&&t| t.unwrap());

...

if skip_special_chars(dep) || existing_task_names.contains(dep) {
}
```

where names is then an array of string references as opposed to having copied the original task strings.

File: src/chompfile.rs [hunk 8]
```diff
@@ -214,36 +213,46 @@ impl ChompTaskMaybeTemplated {
...
+                        dep.to_owned()
```
Comment (guybedford) [inline src/chompfile.rs:239]: Clone at the end is fine, but this should be the only place to do that.

**Comment by Aslemammad** [comment]
Feel free to check it out now! I saw the watcher, and they were absolute paths, still, you can check it out if you want so we get so closer to merging this.

**Comment by guybedford** [comment]
The extensions test failure looks like a valid bug in this PR to me:

> thread 'main' panicked at 'index out of bounds: the len is 35 but the index is 35', src/task.rs:616:32

Can you take a look at that?

**Comment by Aslemammad** [comment]
I cannot reproduce it, is there anyway we let GitHub actions run without permission, so I can debug it here in gh actions without disrupting you for an access.

**Comment by Aslemammad** [comment]
I cannot reproduce it, is there anyway we let GitHub actions run without permission, so I can debug it here in gh actions without disrupting you for an access.

**Comment by guybedford** [comment]
@Aslemammad sure I've added you as a collaborator so you should have permissions now. Also check the commit hash of the chomp extensions repo being tested against to try locally.

**Comment by Aslemammad** [comment]
Thank you so much, Sure.

**Comment by Aslemammad** [comment]
Well, gh actions stopped working apparently, and I'm also running on the latest chomp-extensions repo, so it does not fail.

File: src/task.rs [hunk 9]
```diff
@@ -607,27 +611,32 @@ impl<'a> Runner<'a> {
                     }
                     None => target.to_string(),
                 };
+                dbg!(&self.nodes.len(), &self.nodes, num);
+                /* if (self.file_nodes.get(&file_target).is_none) {
+                    return ;
+                } */
                 match self.file_nodes.get(&file_target) {
```
Comment (guybedford) [inline src/task.rs:618]: Note that file nodes needs to be uniquely keyed by unique file path strings. If you try logging `self.file_nodes`, it could be worth checking that the files are all absolute path keys in there.

**Comment by Aslemammad** [comment]
New error, ncc shows that it does not support absolute paths, and we should change the config, any idea?

**Comment by guybedford** [comment]
@Aslemammad perhaps we should just make the `$TARGET` and `$DEP` environent variables still be relative paths with backtracking as necessary, rather than absolute for backwards compatibility?

**Comment by Aslemammad** [comment]
I got no problem with that, gonna try it, but what is backtracking exactly?

**Comment by Aslemammad** [comment]
It is working now.

File: src/task.rs [hunk 10]
```diff
@@ -1040,15 +1057,32 @@ impl<'a> Runner<'a> {
...
+            diff_paths(Path::new(&target), current_dir().unwrap())
+                .unwrap()
+                .to_str()
+                .unwrap()
+                .to_string()
+        } else {
+            "".to_string()
+        };
+        env.insert("TARGET".to_string(), relative_target.to_owned());
         env.insert("TARGETS".to_string(), targets);
```
Comment (guybedford) [inline src/task.rs:1071]: We should probably make `targets` here also relative to match

File: src/task.rs [hunk 11]
```diff
@@ -1040,15 +1057,32 @@ impl<'a> Runner<'a> {
...
+                .unwrap()
+                .to_str()
+                .unwrap()
+                .to_string()
+        } else {
+            "".to_string()
+        };
+
+        env.insert("DEP".to_string(), relative_dep);
         env.insert("DEPS".to_string(), deps.join(":"));
```
Comment (guybedford) [inline src/task.rs:1086]: And the same for deps.

**Review by guybedford — APPROVED** [review]
Sorry again for the delay, I've been travelling again here. This is looking great and ready to merge! Last point is just to make both "TARGETS" and "DEPS" relative, then please go ahead and merge you don't need another review from me further.

**Comment by Aslemammad** [comment]
Sure, updated them. I may be less available these days, because the government is shutting down the internet and it makes it hard to keep up with coding, Sorry. 

[#MahsaAmini](https://twitter.com/hashtag/MahsaAmini)

**Comment by Aslemammad** [comment]
Sure, updated them. I may be less available these days, because the government is shutting down the internet and it makes it hard to keep up with coding, Sorry. 

[#MahsaAmini](https://twitter.com/hashtag/MahsaAmini)

**Comment by guybedford** [comment]
The core tests seem to be failing now unfortunately. Are you able to update and merge? I can get it landed otherwise.

**Comment by Aslemammad** [comment]
@guybedford Done.

**Comment by guybedford** [comment]
Thanks again for your hard work on this!
