### PR TITLE
fix: better cwd resolving

### LINKED ISSUE #148: Chomp self-build error
With the latest Chomp (0.2.8), `chomp` in Chomp itself is not working:

```
$ chomp
● src/main.rs [cached]
🞂 :build
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
√ :build [407.8866ms]
🞂 :test
√ :test:clean [48.2877ms]
Error: File C:/Users/guybe/Projects/chomp-rs/test/output/lib/dep.js not found
```

This is likely something to do with not using the right cwd.

//cc @Aslemammad (note apart from that, the new version seems to work well in most projects I've tested so far!)

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #148

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -466,7 +466,7 @@ async fn main() -> Result<()> {
     }
 
     let (mut has_templates, mut template_tasks) =
-        expand_template_tasks(&chompfile, &mut extension_env)?;
+        expand_template_tasks(&chompfile, &mut extension_env, cwd.to_string_lossy().to_string().as_str())?;
```
Comment (guybedford) [inline src/main.rs:469]: Just a direct reference should work:

```suggestion
        expand_template_tasks(&chompfile, &mut extension_env, &cwd.to_string_lossy().to_string())?;
```

You may need to make it a variable though:

```suggestion
        let cwd_str = cwd.to_string_lossy().to_string();
        expand_template_tasks(&chompfile, &mut extension_env, &cwd_str)?;
```

**Review by guybedford — APPROVED** [review]
Great, thank you for sorting this one out!
